title: Infraestrutura de Redes de Computadores
description: Material de Estudo sobre Infraestrutura de Redes de Computadores
theme: just-the-docs

url: https://lupamedeiros.github.io/infra-de-redes

aux_links:
  Template Repository: https://github.com/lupamedeiros/infra-de-redes
